// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/6/2026, 3:33:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/rizvee/projects/Organic-aprico-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/plugins/**/*.{js,ts,mjs}","/home/rizvee/projects/Organic-aprico-frontend/composables/**/*.{js,ts,mjs}","/home/rizvee/projects/Organic-aprico-frontend/utils/**/*.{js,ts,mjs}","/home/rizvee/projects/Organic-aprico-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/rizvee/projects/Organic-aprico-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;